# -*- coding: utf-8 -*-
# flake8:noqa
# isort:skip_file
# vim:et:ft=python:nowrap:sts=4:sw=4:ts=4
##############################################################################
# Note: Generated by soapfish.wsdl2py at 2018-01-08 14:19:48.606447
#       Try to avoid editing it if you might need to regenerate it.
##############################################################################

from soapfish import soap, xsd

BaseHeader = xsd.ComplexType

from test_harness.server_schema import *
from test_harness import server_schema

##############################################################################
# Operations


def SendApplicationForms(request, SendApplicationForms):
    # TODO: Put your implementation here.
    SendApplicationFormsResponseplease = server_schema.SendApplicationFormsResponse()
    SendApplicationFormsResponseplease.SendApplicationFormsResult = 'SUCCESS'
    return SendApplicationFormsResponseplease



def GetIndividualsFromSearchCriteria(request, GetIndividualsFromSearchCriteria):
    # TODO: Put your implementation here.
    return GetIndividualsFromSearchCriteriaResponse



def GetIndividualsRegistrations(request, GetIndividualsRegistrations):
    # TODO: Put your implementation here.
    return GetIndividualsRegistrationsResponse



def GetIndividualDetails(request, GetIndividualDetails):
    # TODO: Put your implementation here.
    return GetIndividualDetailsResponse



def SendIndividualDetails(request, SendIndividualDetails):
    # TODO: Put your implementation here.
    return SendIndividualDetailsResponse



def GetELSProviderDetails(request, GetELSProviderDetails):
    # TODO: Put your implementation here.
    return GetELSProviderDetailsResponse



def GetNewURN(request, GetNewURN):
    # TODO: Put your implementation here.
    return GetNewURNResponse



def GetReferenceData(request, GetReferenceData):
    # TODO: Put your implementation here.
    return GetReferenceDataResponse



def SendMessages(request, SendMessages):
    # TODO: Put your implementation here.
    return SendMessagesResponse



def GetOrganisationsFromSearchCriteria(request, GetOrganisationsFromSearchCriteria):
    # TODO: Put your implementation here.
    return GetOrganisationsFromSearchCriteriaResponse



def GetOrganisationDetails(request, GetOrganisationDetails):
    # TODO: Put your implementation here.
    return GetOrganisationDetailsResponse



def GetInvoiceDetails(request, GetInvoiceDetails):
    # TODO: Put your implementation here.
    return GetInvoiceDetailsResponse



def SendAdhocPayment(request, SendAdhocPayment):
    # TODO: Put your implementation here.
    return SendAdhocPaymentResponse



def SendPayment(request, SendPayment):
    # TODO: Put your implementation here.
    return SendPaymentResponse



def GetRegistrationsFromSearchCriteria(request, GetRegistrationsFromSearchCriteria):
    # TODO: Put your implementation here.
    return GetRegistrationsFromSearchCriteriaResponse



def GetRegistrationDetails(request, GetRegistrationDetails):
    # TODO: Put your implementation here.
    return GetRegistrationDetailsResponse



def SendRegistrationDetails(request, SendRegistrationDetails):
    # TODO: Put your implementation here.
    return SendRegistrationDetailsResponse


##############################################################################
# Methods


SendApplicationForms_method = xsd.Method(
    function=SendApplicationForms,
    soapAction='http://127.0.0.1/OfstedOnlineWS/SendApplicationForms',
    input='SendApplicationForms',
    inputPartName='parameters',
    output='SendApplicationFormsResponse',
    outputPartName='parameters',
    operationName='SendApplicationForms',
    style='document',
)


GetIndividualsFromSearchCriteria_method = xsd.Method(
    function=GetIndividualsFromSearchCriteria,
    soapAction='http://127.0.0.1/OfstedOnlineWS/GetIndividualsFromSearchCriteria',
    input='GetIndividualsFromSearchCriteria',
    inputPartName='parameters',
    output='GetIndividualsFromSearchCriteriaResponse',
    outputPartName='parameters',
    operationName='GetIndividualsFromSearchCriteria',
    style='document',
)


GetIndividualsRegistrations_method = xsd.Method(
    function=GetIndividualsRegistrations,
    soapAction='http://127.0.0.1/OfstedOnlineWS/GetIndividualsRegistrations',
    input='GetIndividualsRegistrations',
    inputPartName='parameters',
    output='GetIndividualsRegistrationsResponse',
    outputPartName='parameters',
    operationName='GetIndividualsRegistrations',
    style='document',
)


GetIndividualDetails_method = xsd.Method(
    function=GetIndividualDetails,
    soapAction='http://127.0.0.1/OfstedOnlineWS/GetIndividualDetails',
    input='GetIndividualDetails',
    inputPartName='parameters',
    output='GetIndividualDetailsResponse',
    outputPartName='parameters',
    operationName='GetIndividualDetails',
    style='document',
)


SendIndividualDetails_method = xsd.Method(
    function=SendIndividualDetails,
    soapAction='http://127.0.0.1/OfstedOnlineWS/SendIndividualDetails',
    input='SendIndividualDetails',
    inputPartName='parameters',
    output='SendIndividualDetailsResponse',
    outputPartName='parameters',
    operationName='SendIndividualDetails',
    style='document',
)


GetELSProviderDetails_method = xsd.Method(
    function=GetELSProviderDetails,
    soapAction='http://127.0.0.1/OfstedOnlineWS/GetELSProviderDetails',
    input='GetELSProviderDetails',
    inputPartName='parameters',
    output='GetELSProviderDetailsResponse',
    outputPartName='parameters',
    operationName='GetELSProviderDetails',
    style='document',
)


GetNewURN_method = xsd.Method(
    function=GetNewURN,
    soapAction='http://127.0.0.1/OfstedOnlineWS/GetNewURN',
    input='GetNewURN',
    inputPartName='parameters',
    output='GetNewURNResponse',
    outputPartName='parameters',
    operationName='GetNewURN',
    style='document',
)


GetReferenceData_method = xsd.Method(
    function=GetReferenceData,
    soapAction='http://127.0.0.1/OfstedOnlineWS/GetReferenceData',
    input='GetReferenceData',
    inputPartName='parameters',
    output='GetReferenceDataResponse',
    outputPartName='parameters',
    operationName='GetReferenceData',
    style='document',
)


SendMessages_method = xsd.Method(
    function=SendMessages,
    soapAction='http://127.0.0.1/OfstedOnlineWS/SendMessages',
    input='SendMessages',
    inputPartName='parameters',
    output='SendMessagesResponse',
    outputPartName='parameters',
    operationName='SendMessages',
    style='document',
)


GetOrganisationsFromSearchCriteria_method = xsd.Method(
    function=GetOrganisationsFromSearchCriteria,
    soapAction='http://127.0.0.1/OfstedOnlineWS/GetOrganisationsFromSearchCriteria',
    input='GetOrganisationsFromSearchCriteria',
    inputPartName='parameters',
    output='GetOrganisationsFromSearchCriteriaResponse',
    outputPartName='parameters',
    operationName='GetOrganisationsFromSearchCriteria',
    style='document',
)


GetOrganisationDetails_method = xsd.Method(
    function=GetOrganisationDetails,
    soapAction='http://127.0.0.1/OfstedOnlineWS/GetOrganisationDetails',
    input='GetOrganisationDetails',
    inputPartName='parameters',
    output='GetOrganisationDetailsResponse',
    outputPartName='parameters',
    operationName='GetOrganisationDetails',
    style='document',
)


GetInvoiceDetails_method = xsd.Method(
    function=GetInvoiceDetails,
    soapAction='http://127.0.0.1/OfstedOnlineWS/GetInvoiceDetails',
    input='GetInvoiceDetails',
    inputPartName='parameters',
    output='GetInvoiceDetailsResponse',
    outputPartName='parameters',
    operationName='GetInvoiceDetails',
    style='document',
)


SendAdhocPayment_method = xsd.Method(
    function=SendAdhocPayment,
    soapAction='http://127.0.0.1/OfstedOnlineWS/SendAdhocPayment',
    input='SendAdhocPayment',
    inputPartName='parameters',
    output='SendAdhocPaymentResponse',
    outputPartName='parameters',
    operationName='SendAdhocPayment',
    style='document',
)


SendPayment_method = xsd.Method(
    function=SendPayment,
    soapAction='http://127.0.0.1/OfstedOnlineWS/SendPayment',
    input='SendPayment',
    inputPartName='parameters',
    output='SendPaymentResponse',
    outputPartName='parameters',
    operationName='SendPayment',
    style='document',
)


GetRegistrationsFromSearchCriteria_method = xsd.Method(
    function=GetRegistrationsFromSearchCriteria,
    soapAction='http://127.0.0.1/OfstedOnlineWS/GetRegistrationsFromSearchCriteria',
    input='GetRegistrationsFromSearchCriteria',
    inputPartName='parameters',
    output='GetRegistrationsFromSearchCriteriaResponse',
    outputPartName='parameters',
    operationName='GetRegistrationsFromSearchCriteria',
    style='document',
)


GetRegistrationDetails_method = xsd.Method(
    function=GetRegistrationDetails,
    soapAction='http://127.0.0.1/OfstedOnlineWS/GetRegistrationDetails',
    input='GetRegistrationDetails',
    inputPartName='parameters',
    output='GetRegistrationDetailsResponse',
    outputPartName='parameters',
    operationName='GetRegistrationDetails',
    style='document',
)


SendRegistrationDetails_method = xsd.Method(
    function=SendRegistrationDetails,
    soapAction='http://127.0.0.1/OfstedOnlineWS/SendRegistrationDetails',
    input='SendRegistrationDetails',
    inputPartName='parameters',
    output='SendRegistrationDetailsResponse',
    outputPartName='parameters',
    operationName='SendRegistrationDetails',
    style='document',
)


##############################################################################
# SOAP Service


OfstedOnlineWSSoap_SERVICE = soap.Service(
    name='OfstedOnlineWSSoap',
    targetNamespace='http://127.0.0.1/OfstedOnlineWS',
    location='${scheme}://${host}/OfstedOnlineWS/',
    schemas=[Schema_574e8],
    version=soap.SOAPVersion.SOAP12,
    methods=[SendApplicationForms_method, GetIndividualsFromSearchCriteria_method, GetIndividualsRegistrations_method, GetIndividualDetails_method, SendIndividualDetails_method, GetELSProviderDetails_method, GetNewURN_method, GetReferenceData_method, SendMessages_method, GetOrganisationsFromSearchCriteria_method, GetOrganisationDetails_method, GetInvoiceDetails_method, SendAdhocPayment_method, SendPayment_method, GetRegistrationsFromSearchCriteria_method, GetRegistrationDetails_method, SendRegistrationDetails_method],
)


##############################################################################


# NOTE: Uncomment the following lines to turn on dispatching for Django:
from soapfish.django_ import django_dispatcher
dispatcher = django_dispatcher(OfstedOnlineWSSoap_SERVICE)


# NOTE: Put these lines in the urls.py for your project or application:
# urlpatterns += patterns('',
#     (r'^OfstedOnlineWS\/$', '<module>.dispatcher'),
# )
##############################################################################
