# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant_home_address',
            name='current_address',
            field=models.NullBooleanField(),
        ),
    ]
