# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_personal_details',
            name='birth_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant_personal_details',
            name='birth_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant_personal_details',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
