# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='login_id',
            field=models.ForeignKey(db_column='login_id', on_delete=django.db.models.deletion.CASCADE, to='application.Login_And_Contact_Details'),
        ),
    ]
