# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_eyfs'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='healthdeclarationbooklet',
            table='HDB',
        ),
    ]
