# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20180102_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='login_id',
            field=models.ForeignKey(blank=True, db_column='login_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Login_And_Contact_Details'),
        ),
    ]
