# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_childcare_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_and_contact_details',
            name='add_phone_number',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='login_and_contact_details',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
