# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_applicant_home_address_current_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_and_contact_details',
            name='add_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='login_and_contact_details',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
