# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20171221_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_and_contact_details',
            name='add_phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='login_and_contact_details',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
