# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_application_children_turning_16'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adultinhome',
            name='email',
        ),
    ]
