# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20180130_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='information_correct_declare',
            field=models.NullBooleanField(),
        ),
    ]
