# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-12 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_application_information_correct_declare'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstaidtraining',
            name='renew_certificate',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='firstaidtraining',
            name='show_certificate',
            field=models.NullBooleanField(),
        ),
    ]
