# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-16 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20180212_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
