# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline_logger', '0002_auto_20160624_1045'),
        ('application', '0012_application_date_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineLogger',
            fields=[
                ('timelinelog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timeline_logger.TimelineLog')),
            ],
            bases=('timeline_logger.timelinelog',),
        ),
    ]
