# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 14:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_application_date_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('audit_message', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
            ],
            options={
                'db_table': 'AUDIT_LOG',
            },
        ),
    ]
