# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_timelinelogger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelinelogger',
            name='timelinelog_ptr',
        ),
        migrations.DeleteModel(
            name='TimelineLogger',
        ),
    ]
