# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auditlog'),
        ('application', '0013_auditlog'),
    ]

    operations = [
    ]
